apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-poc
  region: us-east-1
  version: "1.30"
  tags:
    wp:terraform: "false"
    wp:environment: "dev"
    wp:cost-center: "ops"
    wp:owner: "ops"
    wp:managed-by: "eksctl"
    karpenter.sh/discovery: eks-poc  #${CLUSTER_NAME}

vpc:
  id: vpc-0f941eed71c3b0179
  #publicAccessCIDRs: ["10.0.2.0/24", "10.0.9.0/25"]
  securityGroup: sg-06a0beefd0ed45a07
  subnets:
    private:
      us-east-1a: { id: subnet-0ebeafd6054e83d84 }
      us-east-1b: { id: subnet-0e62b2a66ea4235c7 }
     # us-east-1c: { id: subnet-0564dca4816439969 }
    public:
      us-east-1a: { id: subnet-0441e1c0571e6d4a6 }
      us-east-1b: { id: subnet-0b352436511bed6c4 }
      #us-east-1c: { id: subnet-02ab36d3b3700e7fa }
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
cloudWatch:
   clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    logRetentionInDays: 7
iam:
 withOIDC: true
 serviceAccounts:	
 - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
   wellKnownPolicies:
      awsLoadBalancerController: true  
 - metadata:
      name: external-dns
      namespace: kube-system
   wellKnownPolicies:
      externalDNS: true

managednodeGroups:
  - name: eks-pooc-ng
    instanceType: t3a.medium
    amiFamily: AmazonLinux2023
    #privateNetworking: true # Ensures nodes are launched in private subnets
    updateConfig:
      maxUnavailablePercentage: 50
    disableIMDSv1: false
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
    volumeType: gp3
#    volumeEncrypted: true
#    volumeKmsKeyID:  # please see https://docs.aws.amazon.com/autoscaling/ec2/userguide/key
    ssh: # use existing EC2 key
      allow: true
      enableSsm: false
      publicKeyPath: "/root/.ssh/devops.pub"
    securityGroups:
      withShared: true
      attachIDs: ["sg-06a0beefd0ed45a07"]
    maxPodsPerNode: 35
    subnets:
      - subnet-0441e1c0571e6d4a6
      - subnet-0b352436511bed6c4
  #    - subnet-0564dca4816439969	 
    iam:
      instanceProfileARN: "arn:aws:iam::509399617800:instance-profile/eksNodeRole"
      instanceRoleARN: "arn:aws:iam::509399617800:role/eksNodeRole"
    tags:
      alpha.eksctl.io/nodegroup-name: "ops_build_eks_nodegroup"
      alpha.eksctl.io/nodegroup-type: "managed"
    labels: 
      nodegroup-role: "worker" 

addons:
  #- name: aws-ebs-csi-driver
  #  version: latest
  - name: eks-pod-identity-agent
    version: latest 
  - name: vpc-cni
    version: latest # Example version
    attachPolicyARNs:
     - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    # Optional: Add specific config for the CNI if needed
  - name: kube-proxy
    version: latest
    # Optional: Configure settings here
  - name: coredns
    version: latest
#  - name: aws-ebs-csi-driver # Example for a common add-on
#    wellKnownPolicies: # Simplifies IAM setup
#      ebsCSIController: true
  
  
addonsConfig:    
   autoApplyPodIdentityAssociations: true

karpenter:
  version: '0.37.0' # Exact version must be provided
  createServiceAccount: true # default is false
  withSpotInterruptionQueue: true #adds all required policies and rules for supporting Spot Interruption Queue, default is false