apiVersion: v1
kind: Namespace
metadata:
  name: test-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-cronjob-sa
  namespace: test-app
  annotations:
    # Optional: Add if using IRSA for migration
    eks.amazonaws.com/role-arn: arn:aws:iam::509399617800:role/pod-identity-role-ecr-auth # $POD_ROLE_ARN
automountServiceAccountToken: True  # Security best practice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: awscli-app
  #name: awscli-app
  name: awscli-app
  namespace: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awscli-app
  template:
    metadata:
      labels:
        app: awscli-app
    spec:
      serviceAccountName: ecr-cronjob-sa
      containers:
      - name: aws-cli-app
        image: alpine/k8s:1.32.11
        securityContext:
          #runAsNonRoot: true
          #allowPrivilegeEscalation: false
          #runAsUser: 1
        command: 
         - /bin/bash
         - -ce
         - |
          set -e
           # Install AWS CLI
           echo "Installing AWS CLI..."
           apk add --no-cache aws-cli 
