apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-ecr-login
  namespace: test-app
spec:
  #schedule: "*/5 * * * *"
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3 # Retain 3 successful jobs
  failedJobsHistoryLimit: 2 # Retain 2 failed jobs
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure ##  Restart Policy in case container failed
          hostNetwork: true ## this is important for kubcetl to access the host
          serviceAccountName: ecr-cronjob-sa # Reference the service account
          initContainers:
          - name: init-myservice
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ['sh', '-c', 'echo "Initialization started, waiting 5 seconds..." && sleep 5 && echo "Initialization complete."']
          containers:
          - name: my-app
            #image: bitnami/kubectl:latest
            image: alpine/k8s:1.32.11
            imagePullPolicy: IfNotPresent
            command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster    
            #restartPolicy: Never
            #restartPolicy: OnFailure. #only set for non-init containers 